apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana
  namespace: argocd
spec:
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: "{{name}}-grafana"
    spec:
      project: delivery
      syncPolicy:
        automated:
          prune: true
          selfHeal: false
      destination:
        server: "{{server}}"
        namespace: default
      source:
        chart: grafana
        repoURL: https://charts.bitnami.com/bitnami
        targetRevision: 8.2.21
        helm:
          values: |
            admin:
              password: grafana123
            datasources:
              secretDefinition:
                apiVersion: 1
                datasources:
                  - name: Prometheus
                    type: prometheus
                    url: http://delivery-thanos-query.default.svc.cluster.local:9090
                    isDefault: true
